manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: lua
      url-base: https://github.com/tenllado/

  projects:
    - name: lua
      remote: lua
      repo-path: lua
      revision: zephyr
      path: modules/lib/lua
    - name: zephyr
      remote: zephyrproject-rtos
      repo-path: zephyr
      clone-depth: 1
      revision: main
      import: true
      path: zephyr

  self:
    path: app
